# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/noorelyass/PycharmProjects/ExpenseTrackerProject/add_a_purchase.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgAdd(object):
    def setupUi(self, dlgAdd):
        dlgAdd.setObjectName("dlgAdd")
        dlgAdd.resize(435, 481)
        self.layoutWidget = QtWidgets.QWidget(dlgAdd)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 80, 381, 391))
        self.layoutWidget.setObjectName("layoutWidget")
        self.lytMain = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.lytMain.setContentsMargins(0, 0, 0, 0)
        self.lytMain.setObjectName("lytMain")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, 10, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.lblID = QtWidgets.QLabel(self.layoutWidget)
        self.lblID.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblID.setObjectName("lblID")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.lblID)
        self.ledID = QtWidgets.QLineEdit(self.layoutWidget)
        self.ledID.setObjectName("ledID")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.ledID)
        self.lblPurchase = QtWidgets.QLabel(self.layoutWidget)
        self.lblPurchase.setObjectName("lblPurchase")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.lblPurchase)
        self.ledPurchase = QtWidgets.QLineEdit(self.layoutWidget)
        self.ledPurchase.setObjectName("ledPurchase")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.ledPurchase)
        self.lblCost = QtWidgets.QLabel(self.layoutWidget)
        self.lblCost.setObjectName("lblCost")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.lblCost)
        self.dsbCost = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.dsbCost.setMaximum(1000000.0)
        self.dsbCost.setObjectName("dsbCost")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.dsbCost)
        self.lblCategory = QtWidgets.QLabel(self.layoutWidget)
        self.lblCategory.setObjectName("lblCategory")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.lblCategory)
        self.cmbCategory = QtWidgets.QComboBox(self.layoutWidget)
        self.cmbCategory.setObjectName("cmbCategory")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.cmbCategory)
        self.lblWhen = QtWidgets.QLabel(self.layoutWidget)
        self.lblWhen.setObjectName("lblWhen")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.lblWhen)
        self.dteWhen = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dteWhen.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dteWhen.setCalendarPopup(True)
        self.dteWhen.setObjectName("dteWhen")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.dteWhen)
        self.lytMain.addLayout(self.formLayout)
        self.btnAdd = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnAdd.setFont(font)
        self.btnAdd.setObjectName("btnAdd")
        self.lytMain.addWidget(self.btnAdd)
        self.lblTitle = QtWidgets.QLabel(dlgAdd)
        self.lblTitle.setGeometry(QtCore.QRect(40, 40, 371, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTitle.sizePolicy().hasHeightForWidth())
        self.lblTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setStyleSheet("lblAdd{\n"
"    color: red;\n"
"}")
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")

        self.retranslateUi(dlgAdd)
        QtCore.QMetaObject.connectSlotsByName(dlgAdd)

    def retranslateUi(self, dlgAdd):
        _translate = QtCore.QCoreApplication.translate
        dlgAdd.setWindowTitle(_translate("dlgAdd", "Dialog"))
        self.lblID.setText(_translate("dlgAdd", "ID:"))
        self.lblPurchase.setText(_translate("dlgAdd", "Purchase:"))
        self.lblCost.setText(_translate("dlgAdd", "Cost:"))
        self.lblCategory.setText(_translate("dlgAdd", "Category:"))
        self.lblWhen.setText(_translate("dlgAdd", "When?"))
        self.btnAdd.setText(_translate("dlgAdd", "ADD PURCHASE"))
        self.lblTitle.setText(_translate("dlgAdd", "ADD A PURCHASE"))
